#!/bin/bash

# captures a trace 

set -o errexit
set -o xtrace

main () {
	record $1
	generate_flamegraph
}

record () {
	local pid="--pid $1"

	if [[ -z "$1" ]]; then
		pid="-a"
	fi

	perf record \
		--freq 99 \
		"$pid" \
		-g \
		sleep 30
}

generate_flamegraph () {
	perf script | \
		stackcollapse-perf.pl | \
		flamegraph.pl --width=2000 > out.svg
}

main "$@"
